#!/bin/bash

# Define the number of days between update checks
check_interval_days=15

# Define the sudo password
sudo_password="YOUR_SUDO_PASSWORD"

# Loop indefinitely
while true; do
  echo "Checking for updates..."

  # Update package lists
  echo $sudo_password | sudo -S apt update

  # Check if updates are available
  if [[ $(apt list --upgradable 2>/dev/null | grep -c upgradable) -gt 0 ]]; then
    echo "Updates available. Updating and upgrading..."

    # Upgrade packages
    echo $sudo_password | sudo -S apt upgrade -y

    echo "Updates installed successfully!"
  else
    echo "No updates available."
  fi

  # Sleep for the specified number of days
  sleep "$((check_interval_days * 24 * 60 * 60))"
done
